### ISSUE TITLE
Re-check conversions

### ISSUE THREAD

**Issue by matyasselmeci** [opensciencegrid/docs#172]
Going through some of the documents fixing links and am finding conversion issues in several. Keeping a list of files to fix:
- [ ] common/ca.md
- [ ] common/ca_updater.md
  - check condor manual links
- [ ] common/cert_scripts.md
- [ ] compute-element/job_router.md
  - check condor manual links
- [ ] other/gsissh.md

**Comment by brianhlin** [comment]
By conversion issues, do you mean pandoc hanging, missed formatting issues, or something else altogether?

**Comment by matyasselmeci** [comment]
Formatting issues.

**Comment by bbockelm** [comment]
@matyasselmeci - this is 30 days stale.  Is it still relevant or should we close?

**Comment by matyasselmeci** [comment]
Most of the docs are fine (and are no longer named the same thing). I'll tweak ca.md and gsissh.md and call it a day.
