### ISSUE TITLE
Small document issues

### ISSUE THREAD

**Issue by osg-cat** [opensciencegrid/docs#457]
Looking at <https://opensciencegrid.org/docs/security/user-certs/#getting-a-user-certificate>:

* In the first paragraph, the sentence that starts “Examples of this would…” — turn this list into a bullet list for better readability, and maybe introduce the list at the end of the previous sentence: “You need a user certificate if you are going to interact directly with OSG resources or infrastructure, including activities such as:”

* In the “Know your responsibilities” paragraph, I’m pretty sure the email address is incorrect: “For the CILogon RA send email to ca@ciloogon.org.”

* Step 1 of the process should be go to to the CILogon website…

* Current Step 2 (log on) may not actually require your institutional credentials if you are already logged in? I did not have to enter anything when I did this step.

**Comment by matyasselmeci** [comment]
@osg-cat , has this issue been resolved?

**Comment by brianhlin** [comment]
His first bullet still needs to be addressed

**Comment by osg-cat** [comment]
Also, it has been so long since I used this document that I have no real idea whether it is accurate, etc. Follow your standard (?) document testing procedures and, as @brianhlin noted, double-check the initial request, then go ahead and finish the ticket.

**Comment by matyasselmeci** [comment]
My PR just now should have fixed the remaining bullet point so I'm closing this.
